# LibreLane configuration file

DESIGN_NAME: heichips25_template
VERILOG_FILES:
  - dir::../src/heichips25_template.sv
  - dir::../src/alu.v
  - dir::../src/array_serializer.sv
  - dir::../src/clk_div_param.sv
  - dir::../src/clock.v
  - dir::../src/controller.v
  - dir::../src/ir.v
  - dir::../src/reg_file.v
  - dir::../src/serializer.sv
  - dir::../src/top.v
CLOCK_PORT: clk
CLOCK_PERIOD: 20 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

FALLBACK_SDC_FILE: dir::../custom.sdc
# Enable for better SystemVerilog support
#USE_SLANG: true
